name: Automation testing CI
on:
  push:
    branches: [dev, master]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  LANGSMITH_TRACING: ${{ secrets.LANGSMITH_TRACING }}
  LANGSMITH_ENDPOINT: ${{ secrets.LANGSMITH_ENDPOINT }}
  LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
  LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
  GCP_KEY: ${{ secrets.GCP_KEY }}

jobs:

  # ..................................................performance test.......................................................
  performance-only:
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
          # - [self-hosted, Linux]
 
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: hainm112123/Automation-Testing
          ref: dev
          token: ${{ secrets.GHP }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'   
      - run: |
          pip install -r requirements.txt  
          playwright install --with-deps
      
      - run: python tests/runners/performance.py
      
      - uses: ./.github/actions/report
        if: always()
        with:
          NAME: performance-${{join(matrix.runner, '-')}}

  # ..................................................stability test.......................................................
  stability:
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
          # - [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: hainm112123/Automation-Testing
          ref: dev
          token: ${{ secrets.GHP }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'   
      - run: |
          pip install -r requirements.txt  
          playwright install --with-deps

      - run: python tests/runners/stability.py

      - uses: ./.github/actions/report
        if: always()
        with:
          NAME: stability-${{join(matrix.runner, '-')}}

  # ..................................................faul injection test.......................................................
  
  fault-injection:
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
          # - [self-hosted, Linux]
 
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: hainm112123/Automation-Testing
          ref: dev
          token: ${{ secrets.GHP }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'   
      - run: pip install -r requirements.txt
      - if: runner.os == 'Linux' 
        run: |
          sudo apt update
          sudo apt install -y stress-ng
      - if: runner.os == 'Windows'
        uses: ./.github/actions/setup-win-stress
      - if: runner.os == 'macOS' 
        run: brew install stress-ng
      
      - run: python tests/runners/fault.py
      
      - uses: ./.github/actions/report
        if: always()
        with:
          NAME: fault-${{join(matrix.runner, '-')}}
  # ..................................................idle test.......................................................
  idle:
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
          # - [self-hosted, Linux]
 
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: hainm112123/Automation-Testing
          ref: dev
          token: ${{ secrets.GHP }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'   
      - run: pip install -r requirements.txt
      
      - run: python tests/runners/idle.py
      
      - uses: ./.github/actions/report
        if: always()
        with:
          NAME: idle-${{join(matrix.runner, '-')}}
